worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  # Add the Lua package path
  lua_package_path "/usr/local/openresty/lua/?.lua;;";

  # Shared dictionary for rate limiting, caching, etc.
  lua_shared_dict rate_limit_store 10m;
  lua_shared_dict cache_store 50m;

  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;
    
  server_tokens off;
  more_clear_headers Server;

  # Set GOVUK-Request-Id if not set
  map $http_govuk_request_id $govuk_request_id {
    default $http_govuk_request_id;
    ''      "$pid-$msec-$remote_addr-$request_length";
  }

  log_format json_event escape=json '{'
    '"@timestamp":"$time_iso8601",'
    '"body_bytes_sent":$body_bytes_sent,'
    '"bytes_sent":$bytes_sent,'
    '"govuk_request_id":"$govuk_request_id",'
    '"http_host":"$http_host",'
    '"http_referer":"$http_referer",'
    '"http_user_agent":"$http_user_agent",'
    '"http_x_forwarded_for":"$http_x_forwarded_for",'
    '"remote_addr":"$remote_addr",'
    '"remote_user":"$remote_user",'
    '"request_method":"$request_method",'
    '"request_time":$request_time,'
    '"request_uri":"$request_uri",'
    '"sent_http_content_type":"$sent_http_content_type",'
    '"sent_http_location":"$sent_http_location",'
    '"server_protocol":"$server_protocol",'
    '"status":$status'
  '}';

  server {
    listen 80;

    access_log /dev/stdout json_event;
    error_log /dev/stderr;

    location / {
      return 404;
    }

    location = /ok {
      return 200 '200 OK\n';
    }

    location = /redirect {
      return 301 $scheme://$host/redirected;
    }

    location = /redirected {
      default_type text/plain;
      
      return 200 '200 Redirected landing page\n';
    }

    location = /not-found {
      default_type text/plain;

      return 404 '404 Not Found\n';
    }

    location = /internal-server-error {
      default_type text/plain;

      return 500 '500 Internal Server Error\n';
    }

    location = /get {
      default_type text/plain;
      
      limit_except GET { deny all; }

      return 200 '200 GET OK\n';
    }

    location = /post {
      default_type text/plain;
      
      limit_except POST { deny all; }

      return 200 '200 POST OK\n';
    }

    location = /headers/get {
      limit_except GET { deny all; }

      content_by_lua_file "/usr/local/openresty/lua/headers.lua";
    }

    location = /headers/post {
      limit_except POST { deny all; }

      content_by_lua_file "/usr/local/openresty/lua/headers.lua";
    }

    # __canary__ and readyz are standard GOV.UK Endpoints common to all apps

    # Endpoint that isn't cached, which is used to assert that an external
    # service can receive a response from GOV.UK origin on www hostname. It
    # is intended for pingdom monitoring
    location = /__canary__$ {
      default_type application/json;
      add_header cache-control "max-age=0,no-store,no-cache";
      return 200 '{"message": "Tweet tweet"}\n';
    }

    # Endpoint for liveness and readiness checks of the nginx container.
    location = /readyz {
      return 200 'ok\n';
    }
  }
}
