apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fact-check-manager-jwt-auth-secret
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Encryption key for fact check manager JWT token
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: fact-check-manager-jwt-auth-secret
  dataFrom:
    - extract:
        key: govuk/fact-check-manager/jwt-auth-secret