{{- if .Values.alertEnabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
  namespace: monitoring
  labels:
    {{- include "govuk-rails-app.labels" . | nindent 4 }}
    release: prometheus
    app: {{ .Release.Name }}
spec:
  groups: 
    - name: CoreAlerts
      rules:
      {{ .Values.rules | nindent 6 }}
{{- end }}
