apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asset-manager.fullname" . }}
  labels:
    {{- include "asset-manager.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "asset-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "asset-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "asset-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appPort }} 
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: GOVUK_APP_DOMAIN
              value: "{{ .Values.appGovukAppDomain | default (printf "%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.clusterDomain) }}"
            - name: GOVUK_APP_DOMAIN_EXTERNAL
              value: "{{ .Values.appGovukDomainExternal | default (printf "%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
            - name: GOVUK_APP_NAME
              value: "{{ .Values.appGovukAppName | default .Release.Name }}"
            - name: GOVUK_APP_TYPE
              value: "{{ .Values.appGovukAppType }}"
            - name: GOVUK_WEBSITE_ROOT
              value: "{{ .Values.appGovukWebsiteRoot | default (printf "https://www-origin-%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
            - name: DEFAULT_TTL
              value: "{{ .Values.appDefaultTtl }}"
            - name: GOVUK_ASSET_ROOT
              value: "{{ .Values.appGovukAssetRoot | default (printf "https://assets-%s.eks.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
            - name: GOVUK_CONTENT_SCHEMAS_PATH
              value: "{{ .Values.appGovukContentSchemasPath }}"
            - name: GOVUK_ENVIRONMENT
              value: "{{ .Values.govukEnvironment }}"
            - name: PORT
              value: "{{ .Values.appPort }}"
            - name: RAILS_ENV
              value: "{{ .Values.appRailsEnv }}"
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: JWT_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: asset-manager
                  key: jwt_auth_secret
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: asset-manager
                  key: secret_key_base
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: {{ .Release.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginxPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-nginx-conf
        configMap:
          name: {{ .Release.Name }}-nginx-conf

