---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: asset-manager
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  data:
  - secretKey: jwt_auth_secret
    remoteRef:
      key: govuk/asset-manager_app-JWT_AUTH_SECRET
  - secretKey: secret_key_base
    remoteRef:
      key: govuk/asset-manager_app-SECRET_KEYBASE
