{
 "title": "App: request rates, errors, durations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "apps" },
   {
    "name": "app",
    "query": {
     "query": "label_values(http_request_duration_seconds, container)"
    }
   },
   {
    "name": "quantile",
    "label": "quantile",
    "query": {
     "query": "label_values(http_request_duration_seconds{container=\"${app}\"}, quantile)"
    }
   },
   {
    "name": "error_status",
    "label": "HTTP Error Status",
    "query": {
     "query": "label_values(http_requests_total{container=\"${app}\"}, status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "Total requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"${app}\"}[1m]))",
     "legendFormat": "${app}",
     "target": "alias(scaleToSeconds(apps.backend.backend_01.counters.requests.count, 1), 'Requests/s')"
    }
   ]
  },
  {
   "title": "HTTP Request Errors",
   "type": "graph",
   "description": "HTTP Request Errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "Error HTTP Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"${app}\", status=~\"${error_status}\"}[1m])) or vector(0)",
     "legendFormat": "${app}",
     "target": "aliasByNode(apps.fakesite.web_server_01.counters.request_status.{code_500,code_400}.count, 5)"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "description": "Time in Millisecond to process a request",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s", "label": "Time (s)" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds{container=\"${app}\",quantile=~\"${quantile}\"}) BY (quantile)",
     "legendFormat": "{{quantile}} quantile $app"
    }
   ]
  }
 ]
}