{{- $imageTagConfig := $.Files.Get (printf "image-tags/%s/%s" $.Values.govukEnvironment "job-request-operator") | fromYaml }}
{{- $imageTag := $imageTagConfig.image_tag }}
{{- $promoteDeployment := default "false" $imageTagConfig.promote_deployment }}
{{- $autoDeploysEnabled := default "false" $imageTagConfig.automatic_deploys_enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-request-operator
  namespace: {{ $.Values.argoNamespace | default $.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    slackChannel: "#govuk-platform-engineering-support"
    repoName: "alphagov/govuk-job-request-operator/releases"
    imageTag: "{{ $imageTag }}"
    promoteDeployment: "{{ $promoteDeployment }}"
    automaticDeploysEnabled: "{{ $autoDeploysEnabled }}"
    notifications.argoproj.io/subscribe.on-deployed.argo_events: ""
    notifications.argoproj.io/subscribe.deployment.grafana: "deployment|{{ .name }}"
    postSyncWorkflowEnabled: "{{ .postSyncWorkflowEnabled | default "true" }}"
spec:
  project: govuk-operators
  source:
    {{- include "app-config.helm-release"
        ( merge (deepCopy .) (dict "repoURL" "oci://ghcr.io/alphagov/govuk/charts/govuk-job-request-operator" "chart" "govuk-job-request-operator") )
        | nindent 4 }}
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: job-request-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true