apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router-probe-backend
  namespace: {{ $.Values.appsNamespace | default .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com/alphagov/govuk-helm-charts
    path: charts/router-probe-backend
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argoNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
