appResources:
  limits:
    cpu: 1
    memory: 1500Mi
  requests:
    cpu: 0.1
    memory: 800Mi
externalDomainSuffix: eks.integration.govuk.digital
govukEnvironment: integration
govukStack: blue
internalDomainSuffix: apps.svc.cluster.local
publishingServiceDomainSuffix: integration.publishing.service.gov.uk
appImage:
  repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/router
  tag: d6fcffbecf6ab56184370cf32258514cffcb6f87
rules: |rules/router-alerts.yaml
    ## [groups: - name: RouterAlerts   rules:   - alert: RouterBackendHandlerResponseErrorRate     expr: sum(rate(router_backend_handler_response_duration_seconds_count{response_code=~"^5..", job="apps/router"}[5m])) / sum(rate(router_backend_handler_response_duration_seconds_count{job="apps/router"}[5m])) > 0.1     for: 10m     labels:         severity: critical     annotations:         summary: "High error rate for apps/router"         description: "apps/router has high error rate for more than 10 minutes." ]
    #
    #   - alert: RouterBackendHandlerResponseErrorRate
    #     expr: sum(rate(router_backend_handler_response_duration_seconds_count{response_code=~"^5..", job="apps/router"}[5m])) / sum(rate(router_backend_handler_response_duration_seconds_count{job="apps/router"}[5m])) > 0.1
    #     for: 10m
    #     labels:
    #         severity: critical
    #     annotations:
    #         summary: "High error rate for apps/router"
    #         description: "apps/router has high error rate for more than 10 minutes."
    # 
alertEnabled: true
appProbes:
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthcheck
      port: 9394
    periodSeconds: 5
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 2
    httpGet:
      path: /healthcheck
      port: 9394
    periodSeconds: 5
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 10
    httpGet:
      path: /healthcheck
      port: 9394
    periodSeconds: 1
    timeoutSeconds: 1
dnsConfig:
  searches:
  - blue.integration.govuk-internal.digital
extraEnv:
- name: ROUTER_PUBADDR
  value: :3000
- name: ROUTER_APIADDR
  value: :9394
- name: ROUTER_MONGO_URL
  value: router-backend-1,router-backend-2,router-backend-3
- name: BACKEND_URL_collections
  value: http://collections
- name: BACKEND_URL_content-store
  value: http://content-store
- name: BACKEND_URL_email-alert-frontend
  value: http://email-alert-frontend
- name: BACKEND_URL_frontend
  value: http://frontend
- name: BACKEND_URL_government-frontend
  value: http://government-frontend
- name: BACKEND_URL_manuals-frontend
  value: http://manuals-frontend
- name: BACKEND_URL_service-manual-frontend
  value: http://service-manual-frontend
- name: BACKEND_URL_smartanswers
  value: http://smartanswers
- name: BACKEND_URL_static
  value: http://static
- name: BACKEND_URL_whitehall-frontend
  value: http://whitehall-frontend
- name: BACKEND_URL_account-api
  value: https://account-api.integration.govuk-internal.digital
- name: BACKEND_URL_feedback
  value: http://feedback
- name: BACKEND_URL_finder-frontend
  value: http://finder-frontend
- name: BACKEND_URL_info-frontend
  value: http://info-frontend
- name: BACKEND_URL_licencefinder
  value: http://licencefinder
- name: BACKEND_URL_licensify
  value: https://licensify.integration.govuk-internal.digital
- name: BACKEND_URL_search-api
  value: https://search-api.integration.govuk-internal.digital
ingress:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: www-origin
  enabled: true
  hosts:
  - www-origin.eks.integration.govuk.digital
nginxConfigMap:
  create: false
  name: live-router-nginx-conf
nginxExtraVolumeMounts:
- mountPath: /usr/share/nginx/html/robots.txt
  name: live-router-nginx-conf
  subPath: robots.txt
- mountPath: /etc/nginx/htpasswd
  name: router-nginx-htpasswd
nginxExtraVolumes:
- name: router-nginx-htpasswd
  secret:
    secretName: router-nginx-htpasswd
uploadAssets:
  enabled: false

