globalHelmValues:
  govukEnvironment: test
  govukStack: pink  # TODO: eliminate the need for govukStack
  externalDomainSuffix: eks.test.govuk.digital

applications:
- name: argo-workflows
  chartPath: charts/argo-workflows
- name: cluster-secrets
  chartPath: charts/cluster-secrets
- name: govuk-apps-conf
  chartPath: charts/govuk-apps-conf
- name: smokey
  chartPath: charts/smokey
- name: publisher
  ingressHostname: publisher.{{ .Values.globalHelmValues.externalDomainSuffix }}
  helmValues:
    image:
      repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/publisher
      tag: latest  # To be edited by automation (not yet implemented).
    redisUrl: redis://shared-redis-govuk.eks.test.govuk-internal.digital
    replicas: 1
    worker:
      replicas: 1
- name: signon
  helmValues:
    common:
      image:
        repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/signon
        tag: latest  # To be edited by automation (not yet implemented).
      env:
        redisUrl: redis://shared-redis-govuk.eks.test.govuk-internal.digital
    web:
      dbMigrationEnabled: true
      replicas: 1
    worker:
      replicas: 1
- name: router
  helmValues:
    image:
      repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/router
      tag: latest  # To be edited by automation (not yet implemented).
    replicaCount: 1
- name: frontend
  helmValues:
    image:
      repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/frontend
      tag: latest  # To be edited by automation (not yet implemented).
    replicaCount: 1
    appMemcacheServers:
    - frontend-memcached.eks.test.govuk-internal.digital
- name: static
  helmValues:
    image:
      repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/static
      tag: latest  # To be edited by automation (not yet implemented).
    replicaCount: 1
- name: content-store
  helmValues:
    image:
      repository: 172025368201.dkr.ecr.eu-west-1.amazonaws.com/content-store
      tag: latest  # To be edited by automation (not yet implemented).
    replicaCount: 1
    extraEnv:
      - name: ROUTER_API_BEARER_TOKEN
        valueFrom:
          secretKeyRef:
            name: signon-token-content-store-router-api
            key: bearer_token
      - name: GDS_SSO_OAUTH_ID
        valueFrom:
          secretKeyRef:
            name: signon-app-content-store
            key: oauth_id
      - name: GDS_SSO_OAUTH_SECRET
        valueFrom:
          secretKeyRef:
            name: signon-app-content-store
            key: oauth_secret
      - name: appGovukContentSchemasPath
        value: /govuk-content-schemas
      - name: appDefaultTtl:
        value: 1800
      - name: appMongodbUri
        value: mongodb://mongo-1.test.govuk-internal.digital,mongo-2.test.govuk-internal.digital,mongo-3.test.govuk-internal.digital/content_store_production
- name: signon-resources
  chartPath: charts/signon-resources 
