{{- $awsAccountId := .Values.awsAccountId }}
{{ range .Values.namespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-assumer-{{ .namespace }}
  namespace: {{ .namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{- $awsAccountId }}:role/release-assumer
{{ end }}