{
 "title": "Chat AI Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "FE HTTP Total Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "FE HTTP Requests Per Second Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "FE HTTP 5xx Error Rate Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"govuk-chat\", status=~\"5..\"}[$__rate_interval])) / (sum(rate(http_requests_total{job=\"govuk-chat\"}[$__rate_interval])) / 100)",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "FE HTTP Request Duration (P75)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.75, rate(http_request_duration_seconds_sum{job=\"govuk-chat\"}[$__rate_interval]))",
     "legendFormat": "requests/ps"
    },
    {
     "expr": "quantile(0.75, sum(rate(http_request_duration_seconds_sum{job=\"govuk-chat\"}[$__rate_interval])) / sum(rate(http_request_duration_seconds_count{job=\"govuk-chat\"}[$__rate_interval])))",
     "legendFormat": "quantileV2"
    }
   ]
  },
  {
   "title": "FE Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"apps\", pod=~\"govuk-chat-........*-.....\", container=~\"app|nginx\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "FE Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"apps\", pod=~\"govuk-chat-........*-.....\", container=~\"app|nginx\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Worker Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"apps\", pod=~\"govuk-chat-worker-.*\", container=~\"published-documents-consumer|worker\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Worker Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"apps\", pod=~\"govuk-chat-worker-.*\", container=~\"published-documents-consumer|worker\"}) by(container)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Opensearch Cluster Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Opensearch Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Opensearch HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "2xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DomainName": "chat-engine" },
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Read/Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Postgres Read/Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "chat-postgres" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Memory Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Network Bytes In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Bytes Used For Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Redis Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "chat-redis-001" },
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(job, queue) (sidekiq_queue_backlog{job=~\"govuk-chat-worker\"})",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq Work Rate By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, queue) (rate(sidekiq_jobs_total{job=~\"govuk-chat-worker\"}[5m]))",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq Age Of Oldest Job In Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "max by(job, queue) (sidekiq_queue_latency_seconds{job=~\"govuk-chat-worker\"})",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  }
 ]
}