{
 "title": "Database Backups & Syncs",
 "description": "Showing the state of the database backup and sync processes",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_engine",
    "label": "Database Engine",
    "query": {
     "query": "label_values(db_backup_job_state,database_engine)"
    }
   },
   {
    "name": "db_instance",
    "label": "Database Instance",
    "query": {
     "query": "label_values(db_backup_job_state{database_engine=~\"$db_engine\"},database_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Most Recent Backup, Transform, Restore State, Duration, and File size",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "-- In every environment, and every combination of selected database instances within an environment\n-- there are a different sets of metrics that do or don't exist, if they don't exist it causes\n-- grafana to return an empty series which has no labels, and in the SQL expression engine\n-- also has no table. So The PromQL queries get the correct operation, OR both of the others\n-- so in the WITH clause here we filter each series to remove the operations we don't want\n\n-- Additionally since we have no guarantee of any single series existing we need to separately\n-- generate (using the UNION statements below) the distinct list of instances and database names\n-- which exists across all possible metric series. The backup scripts ALWAYS send a state\n-- metric first so we can just query those series. This allows us to use that as the primary\n-- table we join against, thus guaranteeing there is always an instance and database name to\n-- join against\nWITH\n  rState AS (SELECT * FROM RestoreState  WHERE RestoreState.operation=\"restore\"),\n  tState AS (SELECT * FROM TransformState  WHERE TransformState.operation=\"transform\"),\n  bState AS (SELECT * FROM BackupState  WHERE BackupState.operation=\"backup\"),\n  rDuration AS (SELECT * FROM RestoreDuration  WHERE RestoreDuration.operation=\"restore\"),\n  tDuration AS (SELECT * FROM TransformDuration  WHERE TransformDuration.operation=\"transform\"),\n  bDuration AS (SELECT * FROM BackupDuration  WHERE BackupDuration.operation=\"backup\"),\n  rSize AS (SELECT * FROM RestoreSize  WHERE RestoreSize.operation=\"restore\"),\n  bSize AS (SELECT * FROM BackupSize  WHERE BackupSize.operation=\"backup\"),\n  dbs AS (\n    SELECT DISTINCT database_instance, database_db_name FROM rState\n    UNION\n    SELECT DISTINCT database_instance, database_db_name FROM tState\n    UNION\n    SELECT DISTINCT database_instance, database_db_name FROM bState\n  )\nSELECT\n  COALESCE(bState.database_instance, tState.database_instance, rState.database_instance) AS Instance,\n  COALESCE(bState.database_db_name, tState.database_db_name, rState.database_db_name) AS \"Database\",\n  rState.__value__ AS Restore,\n  rDuration.__value__ AS \"R.Duration\",\n  rSize.__value__ AS \"R.Size\",\n  tState.__value__ AS Transform,\n  tDuration.__value__ AS \"T.Duration\",\n  bState.__value__ AS Backup,\n  bDuration.__value__ AS \"B.Duration\",\n  bSize.__value__ AS \"B.Size\"\nFROM dbs\n\nFULL OUTER JOIN rState\n  ON dbs.database_instance = rState.database_instance\n  AND dbs.database_db_name = rState.database_db_name\nFULL OUTER JOIN rDuration\n  ON dbs.database_instance = rDuration.database_instance\n  AND dbs.database_db_name = rDuration.database_db_name\nFULL OUTER JOIN rSize\n  ON dbs.database_instance = rSize.database_instance\n  AND dbs.database_db_name = rSize.database_db_name\n\nFULL OUTER JOIN tState\n  ON dbs.database_instance = tState.database_instance\n  AND dbs.database_db_name = tState.database_db_name\nFULL OUTER JOIN tDuration\n  ON dbs.database_instance = tDuration.database_instance\n  AND dbs.database_db_name = tDuration.database_db_name\n\nFULL OUTER JOIN bState\n ON dbs.database_instance = bState.database_instance\n AND dbs.database_db_name = bState.database_db_name\nFULL OUTER JOIN bDuration\n  ON dbs.database_instance = bDuration.database_instance\n  AND dbs.database_db_name = bDuration.database_db_name\nFULL OUTER JOIN bSize\n  ON dbs.database_instance = bSize.database_instance\n  AND dbs.database_db_name = bSize.database_db_name\n\nORDER BY Instance, \"Database\"",
     "type": "sql"
    }
   ]
  },
  {
   "title": "Time since last Restore/Transform/Backup",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expression": "-- In every environment, and every combination of selected database instances within an environment\n-- there are a different sets of metrics that do or don't exist, if they don't exist it causes\n-- grafana to return an empty series which has no labels, and in the SQL expression engine\n-- also has no table. So The PromQL queries get the correct operation, OR both of the others\n-- so in the WITH clause here we filter each series to remove the operations we don't want\n\n-- Additionally since we have no guarantee of any single series existing we need to separately\n-- generate (using the UNION statements below) the distinct list of instances and database names\n-- which exists across all possible metric series. The backup scripts ALWAYS send a state\n-- metric first so we can just query those series. This allows us to use that as the primary\n-- table we join against, thus guaranteeing there is always an instance and database name to\n-- join against\nWITH\n  r AS (SELECT * FROM Restore WHERE Restore.operation=\"restore\"),\n  t AS (SELECT * FROM Transform WHERE Transform.operation=\"transform\"),\n  b AS (SELECT * FROM Backup WHERE Backup.operation=\"backup\"),\n  dbs AS (\n    SELECT DISTINCT database_instance, database_db_name FROM r\n    UNION\n    SELECT DISTINCT database_instance, database_db_name FROM t\n    UNION\n    SELECT DISTINCT database_instance, database_db_name FROM b\n  )\n\nSELECT\n  COALESCE(b.database_instance, t.database_instance, r.database_instance) AS Instance,\n  COALESCE(b.database_db_name, t.database_db_name, r.database_db_name) AS \"Database\",\n  UNIX_TIMESTAMP() - r.__value__ AS Restore,\n  UNIX_TIMESTAMP() - t.__value__ AS Transform,\n  UNIX_TIMESTAMP() - b.__value__ AS Backup\nFROM dbs\n\nFULL OUTER JOIN b\n  ON dbs.database_instance = b.database_instance\n  and dbs.database_db_name = b.database_db_name\n\nFULL OUTER JOIN t\n  ON dbs.database_instance = t.database_instance\n  and dbs.database_db_name = t.database_db_name\n\nFULL OUTER JOIN r\n  ON dbs.database_instance = r.database_instance\n  AND dbs.database_db_name = r.database_db_name\n\nORDER BY Instance, \"Database\"",
     "type": "sql"
    }
   ]
  },
  { "title": "File Sizes Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$db_instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "repeat": "db_instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(database_db_name, operation) (db_backup_job_file_size_bytes{database_engine=~\"$db_engine\", operation=\"restore\", database_instance=~\"$db_instance\"})",
     "legendFormat": "{{operation}} {{database_db_name}}"
    },
    {
     "expr": "max by(database_db_name, operation) (db_backup_job_file_size_bytes{database_engine=~\"$db_engine\", operation=\"backup\", database_instance=~\"$db_instance\"})",
     "legendFormat": "{{operation}} {{database_db_name}}"
    }
   ]
  },
  { "title": "Durations over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "$db_instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "repeat": "db_instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(database_db_name, operation) (db_backup_job_duration_seconds{database_engine=~\"$db_engine\", operation=\"restore\", database_instance=~\"$db_instance\"})",
     "legendFormat": "{{operation}} {{database_db_name}}"
    },
    {
     "expr": "max by(database_db_name, operation) (db_backup_job_duration_seconds{database_engine=~\"$db_engine\", operation=\"backup\", database_instance=~\"$db_instance\"})",
     "legendFormat": "{{operation}} {{database_db_name}}"
    },
    {
     "expr": "max by(database_db_name, operation) (db_backup_job_duration_seconds{database_engine=~\"$db_engine\", operation=\"transform\", database_instance=~\"$db_instance\"})",
     "legendFormat": "{{operation}} {{database_db_name}}"
    }
   ]
  },
  { "title": "State Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "$db_instance",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "repeat": "db_instance",
   "targets": [
    {
     "expr": "max by(database_instance, database_db_name, operation) (db_backup_job_state{database_engine=~\"$db_engine\", database_instance=~\"$db_instance\"})",
     "legendFormat": "{{operation}} {{database_db_name}}"
    }
   ]
  }
 ]
}