{
 "title": "Dependabot Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "User merged vs auto merged %",
   "type": "timeseries",
   "description": "Shows the percentage of Dependabot pull requests merged by GOV.UK Dependabot Merger vs ones merged by developers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(100 * sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(auto_merged) / (sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(auto_merged) + sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(merged_by_user)))",
     "legendFormat": "auto-merged"
    },
    {
     "expr": "100 * sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(merged_by_user) / (sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(auto_merged) + sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(merged_by_user))",
     "legendFormat": "merged by user"
    }
   ]
  },
  {
   "title": "Total PRs auto-merged vs user merged",
   "type": "timeseries",
   "description": "Shows the total of Dependabot pull requests merged by GOV.UK Dependabot Merger vs ones merged by developers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(merged_by_user)",
     "legendFormat": "merged by user"
    },
    {
     "expr": "sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(auto_merged)",
     "legendFormat": "auto-merged"
    }
   ]
  },
  {
   "title": "Average merge time",
   "type": "timeseries",
   "description": "The average time it takes to merge Dependabot pull requests. This is calculated over the defined interval, allowing for observation of trends in the time it takes for pull requests to be reviewed and merged into the codebase. It takes into account superseded PRs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg (avg_over_time(merge_times[30d:1d]))",
     "legendFormat": "Average merge time"
    }
   ]
  },
  {
   "title": "PRs per update type",
   "type": "timeseries",
   "description": "Shows the trends for major, minor and patch updates.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(sum(prs_per_dependency) without(dependency, dependency_name, container, endpoint, job, namespace, pod, service, timestamp)[7d:1d])",
     "legendFormat": "{{update_type}}"
    }
   ]
  },
  {
   "title": "PRs per dependency",
   "type": "timeseries",
   "description": "Shows the top 5 dependencies that have had the highest average number of PRs associated with them over the past 7 days.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, avg_over_time(sum without(update_type, container, endpoint, job, namespace, pod, service, timestamp) (prs_per_dependency)[7d:1d]))",
     "legendFormat": "{{dependency}}"
    }
   ]
  },
  {
   "title": "Open PRs per dependency",
   "type": "timeseries",
   "description": "Displays the top 10 dependencies based on the average number of open PRs associated with them over the past 7 days. This measure can help identify dependencies that consistently have a high number of open PRs, indicating they might be frequently updated or possibly causing issues that prevent their PRs from being merged.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(sum without(dependency_name, container, timestamp, job, date, endpoint, namespace, pod, service) (open_prs_per_dependency)[7d:1d]))",
     "legendFormat": "{{dependency}}"
    }
   ]
  },
  {
   "title": "PRs per update type and dependency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(sum without(container, endpoint, job, namespace, pod, service, timestamp) (prs_per_dependency)[7d:1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average merge time per repo",
   "type": "timeseries",
   "description": "Shows the top 5 repositories with the longest average merge times over the defined interval. This can indicate repositories where the code review process takes more time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "topk(5, avg by(repo) (avg_over_time(merge_times[$__interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(sum without(container,endpoint,date,job,namespace,pod,timestamp,service)(total_new_prs)[7d:1d])",
     "legendFormat": "total new prs"
    },
    {
     "expr": "sum without(container, endpoint, date, job, namespace, pod, timestamp, service) (total_closed_prs)",
     "legendFormat": "total closed prs"
    },
    {
     "expr": "sum without(container, endpoint, date, job, namespace, pod, timestamp, service) (total_merged_prs)",
     "legendFormat": "total merged prs"
    },
    {
     "expr": "sum without(container, endpoint, date, job, namespace, pod, timestamp, service) (total_open_prs)",
     "legendFormat": "total open prs"
    }
   ]
  },
  {
   "title": "Frequently update repos",
   "type": "timeseries",
   "description": "Presents the top 10 repositories that receive the most frequent updates over the past 7 days. These might be active or critical repositories requiring regular maintenance or updates.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(frequently_updated_repos[30d]))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Open failing PRs",
   "type": "piechart",
   "description": "Displays the total number of open pull requests for each repository that are currently failing their checks. This can indicate repositories where there might be frequent issues or complications.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(repo) (open_failing_prs)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Open PRs",
   "type": "timeseries",
   "description": "Shows the top 10 repositories with the highest average number of open pull requests over the past 7 days.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(sum by(repo) (open_prs)[7d:1d]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Security alerts per dependency",
   "type": "timeseries",
   "description": "Represents the top 10 dependencies that have the most security alerts associated with them. This can highlight dependencies that pose a higher risk and require more scrutiny for potential security vulnerabilities.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "topk by(dependency) (10, sum without(container, timestamp, job, date, endpoint, namespace, pod, service) (security_alerts_per_dependency))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Security alerts per repo",
   "type": "timeseries",
   "description": "Displays the total number of open security alerts for each repository. This provides an overview of potential security vulnerabilities across your projects.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum without(container, timestamp, job, date, endpoint, namespace, pod, service) (security_alerts_per_repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}