{
 "title": "GOV.UK Search API V2",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of usage",
   "type": "timeseries",
   "description": "The rate (requests per minute) of usage of each endpoint measured over a rolling 5 minute period.",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(controller) (rate(http_requests_total{job=\"search-api-v2\", controller!=\"other\"}[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "stat",
   "description": "The number of requests to each endpoint in the selected time period",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller) (increase(http_requests_total{\n    namespace=\"apps\",\n    job=\"search-api-v2\",\n    controller!=\"other\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "description": "Estimated cost of search requests in the selected period.\n\nThis is a rough estimate based on approximate query count, and does not include fixed costs, data storage costs, and ancillary service costs (such as BigQuery).",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_requests_total{\n    namespace=\"apps\",\n    job=\"search-api-v2\",\n    controller=\"searches\"\n}[$__range])) * (1.5/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search requests to Search API v2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Error rate",
   "type": "stat",
   "description": "Percentage of unsuccessful requests to the searches controller.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (increase(http_requests_total{job=\"search-api-v2\", controller=\"searches\", status!=\"200\"}[$__range])) / sum by (controller) (increase(http_requests_total{job=\"search-api-v2\", controller=\"searches\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "description": "5 minute rolling success rate (200 response codes out of all requests) for search requests",
   "gridPos": { "h": 8, "w": 16, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"search-api-v2\", controller=\"searches\", status=\"200\"}[5m]))\n/\nsum(rate(http_requests_total{job=\"search-api-v2\", controller=\"searches\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "description": "Total number of unsuccessful requests to the searches controller.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (increase(http_requests_total{job=\"search-api-v2\",controller=\"searches\",status!=\"200\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autocomplete requests to Search API v2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Max suggestions over last hour",
   "type": "stat",
   "description": "Maximum number of suggestions returned from Discovery Engine over the last hour relative to the end of the highlighted range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (increase(search_api_v2_discovery_engine_autocomplete_suggestions_response_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max suggestions",
   "type": "timeseries",
   "description": "Maximum number of suggestions returned from Discovery Engine over the previous hour.",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (increase(search_api_v2_discovery_engine_autocomplete_suggestions_response_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Empty suggestion rate",
   "type": "timeseries",
   "description": "Percentage of requests to Discovery Engine over the previous hour that return zero suggestions.",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(increase(search_api_v2_discovery_engine_autocomplete_suggestions_response_bucket{le=\"0.0\"}[1h])) / sum(increase(search_api_v2_discovery_engine_autocomplete_suggestions_response_bucket{le=\"5.0\"}[1h]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Empty suggestion rate",
   "type": "stat",
   "description": "Percentage of requests to Discovery Engine over the highlighted range that return zero suggestions.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(search_api_v2_discovery_engine_autocomplete_suggestions_response_bucket{le=\"0.0\"}[$__range])) / sum(increase(search_api_v2_discovery_engine_autocomplete_suggestions_response_bucket{le=\"5.0\"}[$__range]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhandled errors",
   "type": "stat",
   "description": "Total number of unsuccessful requests to the autocompletes controller. This does not include specific errors from Discovery Engine, which are handled internally.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (increase(http_requests_total{job=\"search-api-v2\",controller=\"autocompletes\",status!=\"200\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency and response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Search APIv2 latency: Search Requests",
   "type": "timeseries",
   "description": "Time to serve search results from Search API v2 (HTTP response time)\n\nGreen = satisfied\nYellow = tolerating\nRed = frustrated",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"search-api-v2\", controller=\"searches\"}[5m])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"search-api-v2\", controller=\"searches\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"search-api-v2\", controller=\"searches\"}[5m])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Search APIv2 latency: Autocomplete requests",
   "type": "timeseries",
   "description": "Time to serve autocomplete results from Search API v2 (HTTP response time)\n\nGreen = satisfied\nYellow = tolerating\nRed = frustrated",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"search-api-v2\", controller=\"autocompletes\"}[5m])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"search-api-v2\", controller=\"autocompletes\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"search-api-v2\", controller=\"autocompletes\"}[5m])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Google Cloud Discovery Engine response times: Search",
   "type": "timeseries",
   "description": "Duration of response from Google Cloud Discovery Engine (previously known as 'Vertex AI Search') to a search request (in seconds)",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(search_api_v2_discovery_engine_search_request_duration_bucket[5m])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(search_api_v2_discovery_engine_search_request_duration_bucket[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(search_api_v2_discovery_engine_search_request_duration_bucket[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(search_api_v2_vertex_search_request_duration_bucket[5m])))",
     "legendFormat": "Median (old)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(search_api_v2_vertex_search_request_duration_bucket[5m])))",
     "legendFormat": "90th percentile (old)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(search_api_v2_vertex_search_request_duration_bucket[5m])))",
     "legendFormat": "99th percentile (old)"
    }
   ]
  },
  {
   "title": "Google Cloud Discovery Engine response times: Autocomplete",
   "type": "timeseries",
   "description": "Duration of response from Google Cloud Discovery Engine (previously known as 'Vertex AI Search') to an autocomplete request (in seconds)",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(search_api_v2_discovery_engine_autocomplete_request_duration_bucket[5m])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(search_api_v2_discovery_engine_autocomplete_request_duration_bucket[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(search_api_v2_discovery_engine_autocomplete_request_duration_bucket[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(search_api_v2_vertex_autocomplete_request_duration_bucket[5m])))",
     "legendFormat": "Median (old)"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(search_api_v2_vertex_autocomplete_request_duration_bucket[5m])))",
     "legendFormat": "90th percentile (old)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(search_api_v2_vertex_autocomplete_request_duration_bucket[5m])))",
     "legendFormat": "99th percentile (old)"
    }
   ]
  },
  {
   "title": "Goal: Our users are provided high quality results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Binary Recall top 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(month) (search_api_v2_evaluation_monitoring_recall{top=\"3\", dataset=\"binary\", month=\"this_month\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clickstream NDCG top 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(month) (search_api_v2_evaluation_monitoring_ndcg{dataset=\"clickstream\", top=\"10\", month=\"this_month\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}