{
 "title": "Graphql stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "graphql_document_type",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket{namespace=\"apps\", job=\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"},document_type)"
    }
   },
   {
    "name": "content_store_document_type",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{namespace=\"apps\", job=\"content-store\", controller=\"content_items\", action=\"show\"},document_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "10 Slowest Content Store document types (Last 6 hours)",
   "type": "table",
   "description": "10 slowest average response times to content store, broken up by document type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (document_type) (rate(http_request_duration_seconds_sum{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\"}[6h])) / sum by (document_type) (rate(http_request_duration_seconds_count{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\"}[6h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "10 Slowest GraphQL document types (Last 6 hours)",
   "type": "table",
   "description": "10 slowest average response times to GraphQL, broken up by document type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (document_type) (rate(http_request_duration_seconds_sum{job=\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"}[6h])) / sum by (document_type) (rate(http_request_duration_seconds_count{job=\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"}[6h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests to content store (6h)",
   "type": "stat",
   "description": "Total number of requests to content store, across all pods, for pieces of content over the past 6 hours",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\", status=\"200\"}[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total graphql requests (6 hours)",
   "type": "stat",
   "description": "Total number of graphql requests over the last 6 hours",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{namespace=\"apps\", job=~\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"}[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proportion of graphql vs content-store requests",
   "type": "gauge",
   "description": "Percentage of requests in the last 6 hours which have gone to graphql vs content-store",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(increase(http_requests_total{namespace=\"apps\", job=~\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"}[6h]))) / (sum(increase(http_requests_total{namespace=\"apps\", job=~\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"}[6h])) + sum(increase(http_requests_total{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\"}[6h])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Content store visualisations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Median Request Duration",
   "type": "timeseries",
   "description": "Median request duration by document type",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (document_type, le) (rate(http_request_duration_seconds_bucket{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\", document_type=~\"$content_store_document_type\"}[$__rate_interval])))",
     "legendFormat": "{{document_type}}"
    }
   ]
  },
  {
   "title": "99% Request Duration",
   "type": "timeseries",
   "description": "99th percentile of median response times by document type. This acts as an upper limit of median response time.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (document_type, le) (rate(http_request_duration_seconds_bucket{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\", document_type=~\"$content_store_document_type\"}[$__rate_interval])))",
     "legendFormat": "{{document_type}}"
    }
   ]
  },
  {
   "title": "Total content-store requests per second ",
   "type": "timeseries",
   "description": "Total requests per second for regular content store. Compare with the visualisation below if you want to see the difference between content-store and graphql traffic.\n\nI've made these two separate and it  was helpful to have a separate Y axis for graphql to stop it being hard to read. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"apps\", job=~\"content-store\", controller=\"content_items\", action=\"show\"}[$__rate_interval])) by (job)",
     "legendFormat": "All Document types"
    }
   ]
  },
  { "title": "Graphql visualisations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Median Request Duration",
   "type": "timeseries",
   "description": "Median request duration by document type",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (document_type, le) (rate(http_request_duration_seconds_bucket{namespace=\"apps\", job=~\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\", document_type=~\"$graphql_document_type\"}[$__rate_interval])))",
     "legendFormat": "{{document_type}}"
    }
   ]
  },
  {
   "title": "99% Request Duration",
   "type": "timeseries",
   "description": "99th percentile of median response times by document type. This acts as an upper limit of median response time, which ideally should be under 0.1s",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (document_type, le) (rate(http_request_duration_seconds_bucket{namespace=\"apps\", job=~\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\", document_type=~\"$graphql_document_type\"}[$__rate_interval])))",
     "legendFormat": "{{document_type}}"
    }
   ]
  },
  {
   "title": "Total graphql requests per second ",
   "type": "timeseries",
   "description": "Total requests per second for the read-replica. Spikes should track fairly evenly with load tests. Should be helpful to compare traffic against jumps in response time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"apps\", job=~\"publishing-api-read-replica\", controller=\"graphql\", action=\"execute\"}[$__rate_interval])) by (job)",
     "legendFormat": "All Document types"
    }
   ]
  }
 ]
}