{
 "title": "Publishing API Database - Editions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "publishing_app",
    "query": {
     "query": "label_values(editions_in_database_total,publishing_app)"
    }
   },
   {
    "name": "document_type",
    "query": {
     "query": "label_values(editions_in_database_total,document_type)"
    }
   },
   {
    "name": "locale",
    "query": {
     "query": "label_values(editions_in_database_total,locale)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Proportions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Editions By State",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (editions_in_database_total{publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale=~\"$locale\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Linear bar charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Published Editions By Document Type (linear scale)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sort_desc(sum by (document_type) (editions_in_database_total{state=\"published\", content_store=\"live\", publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale=~\"$locale\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published Editions By Publishing App (linear scale)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sort_desc(sum by (publishing_app) (editions_in_database_total{state=\"published\", content_store=\"live\", publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale=~\"$locale\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-English Editions By Locale (linear scale)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (locale) (editions_in_database_total{publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale!=\"en\", locale=~\"$locale\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logarithmic bar charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Published Editions By Document Type (log scale)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sort_desc(sum by (document_type) (editions_in_database_total{state=\"published\", content_store=\"live\", publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale=~\"$locale\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published Editions By Publishing App (log scale)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sort_desc(sum by (publishing_app) (editions_in_database_total{state=\"published\", content_store=\"live\", publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale=~\"$locale\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Editions By Locale (log scale)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (locale) (editions_in_database_total{publishing_app=~\"$publishing_app\", document_type=~\"$document_type\", locale=~\"$locale\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}