{
 "title": "Sidekiq: queue length, max delay | Redis: memory usage, disk usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(sidekiq_queue_backlog,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(sidekiq_queue_backlog{namespace=\"${namespace}\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (job, queue) (sidekiq_queue_backlog{namespace=\"${namespace}\", job=~\"${app}\"})",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Work rate by queue",
   "type": "timeseries",
   "description": "Per-second rate of processed jobs by queue, 5m moving mean.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job, queue) (rate(sidekiq_jobs_total{namespace=\"${namespace}\", job=~\"${app}\"}[5m]))",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Age of oldest job in queue",
   "type": "timeseries",
   "description": "Age of the oldest job in the Sidekiq queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "max by (job, queue) (sidekiq_queue_latency_seconds{namespace=\"${namespace}\", job=~\"${app}\"})",
     "legendFormat": "{{job}}:{{queue}}"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "global:redis:memory_usage_percentage{pod=~\"$app-redis-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$app-redis.*\", namespace=\"$namespace\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$app-redis.*\", namespace=\"$namespace\"} * 100)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}