groups:
  - name: SearchApiV2BaseMetrics
    rules:
      - record: search_api_v2:search:requests:total
        expr: >-
          sum by() (http_requests_total{
            job="search-api-v2", controller="searches", action="show"
          })
      - record: search_api_v2:search:requests:success_total
        expr: >-
          sum by() (http_requests_total{
            job="search-api-v2", controller="searches", action="show", status="200"
          })

  - name: SearchApiV2DerivedMetrics
    rules:
      - record: search_api_v2:search:success_rate:5m
        expr: >-
          min(
            (
              rate(search_api_v2:search:requests:success_total[5m])
              /
              rate(search_api_v2:search:requests:total[5m])
            ),
            1
          )

      - record: search_api_v2:search:success_rate:30m
        expr: >-
          min(
            (
              rate(search_api_v2:search:requests:success_total[30m])
              /
              rate(search_api_v2:search:requests:total[30m])
            ),
            1
          )

      - record: search_api_v2:search:success_rate:2h
        expr: >-
          min(
            (
              rate(search_api_v2:search:requests:success_total[2h])
              /
              rate(search_api_v2:search:requests:total[2h])
            ),
            1
          )
