apiVersion: v1
kind: Service
metadata:
  name: argo-events-github-service
spec:
  type: ClusterIP
  ports:
    - name: github-deployments
      port: 13000
      targetPort: 13000
  selector:
    eventsource-name: github
