# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: job-request-annotator
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: job-request-annotator
spec:
  commonName: api.job-request-annotator.svc
  dnsNames:
    - api.job-request-annotator.svc.cluster.local 
    - api.job-request-annotator.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: self-signed-cert


