apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: job-request-annotator
  labels:
    app: api
spec:
  ports:
    - name: http
      port: 443
      targetPort: 3000
  selector:
    name: api


