{
 "title": "App: request rates, errors, durations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_requests_total,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(http_request_duration_seconds{namespace=\"${namespace}\"}, job)"
    }
   },
   {
    "name": "quantile",
    "label": "quantile",
    "query": {
     "query": "label_values(http_request_duration_seconds{namespace=\"${namespace}\"}, quantile)"
    }
   },
   {
    "name": "error_status",
    "label": "HTTP Error Status",
    "query": {
     "query": "label_values(http_requests_total{namespace=\"${namespace}\"}, status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"${namespace}\", job=~\"${app}\"}[$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{namespace=\"${namespace}\"}[$__rate_interval]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Toteal HTTP Request Errors per second",
   "type": "timeseries",
   "description": "HTTP Request Errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"${namespace}\", job=~\"${app}\", status=~\"${error_status}\"}[$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{namespace=\"${namespace}\", status=~\"${error_status}\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "description": "Time in Millisecond to process a request",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds{namespace=\"${namespace}\", job=~\"${app}\",quantile=~\"${quantile}\"}) by (job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(http_request_duration_seconds{namespace=\"${namespace}\", quantile=~\"${quantile}\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Request duration per App/Controller/Action",
   "type": "timeseries",
   "description": "Controller Action times sorted by application and sortable by maximum time taken",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(avg without (pod, instance) (http_request_duration_seconds{namespace=\"${namespace}\", job=~\"${app}\", quantile=~\"${quantile}\"}), \"a\", \"$1\", \"job\", \"(.*)\")",
     "legendFormat": "{{job}} {{controller}} {{action}} {{quantile}}",
     "sort": "current"
    }
   ]
  }
 ]
}