{
 "title": "Fastly Dashboard",
 "tags": [ "Fastly" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(fastly_rt_requests_total, service_name)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(fastly_rt_requests_total, service_id)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(fastly_rt_requests_total, datacenter)"
    }
   },
   { "name": "window", "label": "window", "query": "60s" }
  ]
 },
 "panels": [
  {
   "title": "Cache hits per second",
   "type": "stat",
   "description": "Number of user requests per second delivered from cache.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n"
    }
   ]
  },
  {
   "title": "Ratio of cache hits to total user requests per second ",
   "type": "gauge",
   "description": "Requests delivered from cache divided by the number of cacheable requests (hits + misses) per second.",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window])) / (sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n+ sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window])))\n"
    }
   ]
  },
  {
   "title": "Cache processing time in ms",
   "type": "stat",
   "description": "Average millisecond interval from a cache receiving a HTTP request to it sending a cached response's first byte. Also know as Time-To-First-Byte (TTFB).",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(fastly_rt_hits_time_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))"
    }
   ]
  },
  {
   "title": "Cache misses per second",
   "type": "stat",
   "description": "Number of user requests per second for objects not in cache (i.e. cache miss).",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "description": "Total number of requests per second.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "stat",
   "description": "Number of user requests per second producing an error.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n"
    }
   ]
  },
  {
   "title": "Origin response time in ms",
   "type": "stat",
   "description": "Average ms interval from when a cache issues a HTTP request to the origin to when the response is received.",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(fastly_rt_miss_time_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "description": "This number reflects a variety of errors, which can include calls on vcl_error.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))",
     "legendFormat": "errors per second"
    }
   ]
  },
  {
   "title": "Ratio of cache hits to total user requests per second",
   "type": "graph",
   "description": "Hit ratio is defined as the proportion if cache hits to all cacheable content (hits + misses). Increasing your hit ratio improves the overall performance benefit of using Fastly.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window])) / (sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n+ sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window])))\n",
     "legendFormat": "HIT RATIO"
    }
   ]
  },
  {
   "title": "Response body size per second (bandwidth) sent by Fastly",
   "type": "graph",
   "description": "The amount of bandwidth served for you site by Fastly.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(fastly_rt_body_size_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))\n",
     "legendFormat": "response bandwidth"
    }
   ]
  },
  {
   "title": "Events per second",
   "type": "graph",
   "description": "The total number of requests that were received for your site by Fastly.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Events per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))",
     "legendFormat": "cache errors"
    },
    {
     "expr": "sum(rate(fastly_rt_miss_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))",
     "legendFormat": "cache misses"
    },
    {
     "expr": "sum(rate(fastly_rt_hits_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))",
     "legendFormat": "cache hits"
    },
    {
     "expr": "sum(rate(fastly_rt_synth_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))",
     "legendFormat": "synthetic responses"
    },
    {
     "expr": "sum(rate(fastly_rt_pass_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window]))",
     "legendFormat": "uncached responses (passes)"
    }
   ]
  },
  {
   "title": "Origin latency in seconds",
   "type": "heatmap",
   "description": "Displays a histogram showing the distribution of origin latency times in seconds.  This tells you how quickly your origin is responding to Fastly.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(fastly_rt_miss_duration_seconds_bucket{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$window])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}