{
 "title": "Router: request rates, errors, durations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(router_backend_handler_response_duration_seconds_count,namespace)"
    }
   },
   {
    "name": "backend_app",
    "query": {
     "query": "label_values(router_backend_handler_response_duration_seconds_count{namespace=\"${namespace}\"}, backend_id)"
    }
   },
   {
    "name": "quantile",
    "label": "quantile",
    "query": "0.99, 0.95, 0.9, 0.5, 0.1, 0.01"
   },
   {
    "name": "error_status",
    "label": "HTTP Error Status",
    "query": {
     "query": "label_values(router_backend_handler_response_duration_seconds_count{namespace=\"${namespace}\"}, response_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "Total requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(router_backend_handler_response_duration_seconds_count{job=\"${namespace}/router\", backend_id=~\"${backend_app}\"}[$__rate_interval])) by (backend_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(router_backend_handler_response_duration_seconds_count{job=\"${namespace}/router\"}[$__rate_interval]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "HTTP request errors per second",
   "type": "graph",
   "description": "HTTP request errors per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "Error HTTP Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(router_backend_handler_response_duration_seconds_count{job=\"${namespace}/router\", backend_id =~ \"${backend_app}\",response_code=~\"${error_status}\"}[$__rate_interval])) by (backend_id)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(router_backend_handler_response_duration_seconds_count{job=\"${namespace}/router\",response_code=~\"${error_status}\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "description": "Time in Millisecond to process a request",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile}, sum(rate(router_backend_handler_response_duration_seconds_bucket{job=\"${namespace}/router\", backend_id=~\"${backend_app}\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}