---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "db-sync.fullname" . }}-passwd
  labels:
    {{- include "db-sync.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >
      Map of hostname to aws_db_admin password for backup/restore of databases
      hosted in RDS. The required key is the one used by the consuming job, 
      which defaults tothe pub name unless overridden by chart values. 
      TODO: stop using passwords.
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    deletionPolicy: {{ .Values.externalSecrets.deletionPolicy }}
    name: {{ include "db-sync.fullname" . }}-passwd
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.secretKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
