name: Lint GitHub Actions
on:
  push:
    paths: ['.github/**']

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          show-progress: false
      - uses: alphagov/govuk-infrastructure/.github/actions/actionlint@a76c1ffc2c5fe5177113124478faa224e3a44f00 # main
