name: Router probe backend tests
on:
  pull_request:
    paths:
      - charts/router-probe-backend/**
  push:
    branches:
      - main
    paths:
      - charts/router-probe-backend/**

permissions:
  contents: read

jobs:
  test-backend:
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   # v7.0.0
        with:
          show-progress: false
      - working-directory: charts/router-probe-backend/tests
        shell: bash
        run: ./run-tests.sh
