name: Router probe backend tests
on:
  pull_request:
    paths:
      - charts/router-probe-backend/**
  push:
    branches:
      - main
    paths:
      - charts/router-probe-backend/**

permissions:
  contents: read

jobs:
  test-backend:
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
        with:
          show-progress: false
      - working-directory: charts/router-probe-backend/tests
        shell: bash
        run: ./run-tests.sh
