name: linting
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          show-progress: false

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310   # v5.0.1

      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7   # v10.2.0

      - name: Render apps
        run: ./bin/render-argo-apps.py --lint

      - name: kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest-alpine
        with:
          entrypoint: /kubeconform
          args: >
            -kubernetes-version 1.36.3
            -schema-location default
            -schema-location
            "https://alphagov.github.io/govuk-crd-library/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"
            -schema-location
            "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ .NormalizedKubernetesVersion }}/api/openapi-spec/v3/apis__apiextensions.k8s.io__v1_openapi.json"
            -ignore-filename-pattern ".*/Chart.yaml"
            -summary
            -strict
            output

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          show-progress: false
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38  # 2.0.0
        env:
          SHELLCHECK_OPTS: -xP SCRIPTDIR

  yamllint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          show-progress: false
      - run: make lint

  promtool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
        with:
          show-progress: false
      - name: Run promtool checks
        uses: ./.github/actions/promtool
        with:
          args: >
            check rules $(find charts/monitoring-config/rules -name '*.yaml' \
              -not -name '*_tests.yaml')
      - name: Run promtool tests
        uses: ./.github/actions/promtool
        with:
          args: test rules $(find charts/monitoring-config/rules -name '*_tests.yaml')
