name: Update image tag

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
        type: string
      repo:
        description: 'The application repository'
        required: true
        type: string
        default: 'collections'
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
        - integration
        - staging
        - production
        default: 'integration'
      manual_deploy:
        description: 'Manual deploy'
        required: true
        type: boolean

jobs:
  update-image-tag:

    permissions: write-all
    runs-on: ubuntu-latest
    env:
      repo: ${{ inputs.repo }}
      image_tag: ${{ inputs.image_tag }}
      environment: ${{ inputs.environment }}
      branch: "update-image-tag/${{ inputs.repo }}/${{ inputs.environment }}/${{ inputs.image_tag }}"
      config_file: "charts/argocd-apps/image-tags/${{ inputs.environment }}/${{ inputs.repo }}"
    steps:
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: '4.27.2'
          yq-url: 'https://github.com/mikefarah/yq/releases/download/v4.27.2/yq_linux_amd64'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get latest commit SHA for repository
        id: get-sha
        run: |
          LATEST_COMMIT_SHA=$(git ls-remote "https://github.com/alphagov/${repo}" HEAD | cut -f 1)
          echo "::set-output name=latest_commit_sha::${LATEST_COMMIT_SHA}"

      - name: Update image tag
        id: update-image-tag
        if: steps.get-sha.outputs.latest_commit_sha == env.image_tag || inputs.manual_deploy
        run: |
          git checkout -b "${branch}"

          yq -i '.image_tag = env(image_tag)' "${config_file}"

          UPDATED=$([ -z `git status --porcelain` ] && echo 'false' || echo 'true')
          echo "::set-output name=updated::${UPDATED}"

      - name: Push changes
        if: steps.update-image-tag.outputs.updated
        run: |
          git config --global user.name '${{ github.triggering_actor }}'
          git config --global user.email "${{ github.triggering_actor }}@users.noreply.github.com"

          git add "${config_file}"
          git commit -m "Update ${repo} image tag to ${image_tag} for ${environment}"

          # git push -u origin "${branch}"
          # gh api repos/alphagov/govuk-helm-charts/merges -f head="${branch}" -f base=main
          # git push origin --delete "${branch}"

          echo "Pushed changes to GitHub"
